### ISSUE TITLE
Change image name location in pod template

### ISSUE THREAD

**Issue by dmartin35** [chaostoolkit-incubator/kubernetes-crd#12]
We currently have nested block for defining the ChaosExperiment POD image in the POD template, 
```
spec:
  namespace: chaostoolkit-run
  pod:
    image:
      name: my/chaostoolkit
```

This sub level shall be removed , to have simpler description

```
spec:
  namespace: chaostoolkit-run
  pod:
    image: my/chaostoolkit
```

requires code, tests, readme & CTK doc to be updated
