### ISSUE TITLE
Install CTK extensions at runtime

### ISSUE THREAD

**Issue by dmartin35** [chaostoolkit-incubator/kubernetes-crd#20]
Currently, to use the CTK with extension, we need to create a new docker image that includes the desired plugins. This solution is not very flexible, unless creating a big image that contains all possible extensions.

Could we / would we provide a way to specify the list of CTK extensions to be used by the ChaosExperiment CRO  ?

we could provide something like:
```
---
apiVersion: chaostoolkit.org/v1
kind: ChaosToolkitExperiment
metadata:
  name: my-chaos-exp
  namespace: chaostoolkit-crd
spec:
  pod:
    extensions:
    - chaostoolkit-slack
    - chaostoolkit-kubernetes
```  

Can we do the `pip install ` within an init-container ? 

Drawback, dynamic extensions installation will be done at each runtime, will slow down the start of running the experiment. But this might not be very critical if we think extensions flexibility is a gain.
