### ISSUE TITLE
Load kubernetes secrets as environment

### ISSUE THREAD

**Issue by dmartin35** [chaostoolkit-incubator/kubernetes-crd#38]
We currently can only load environment variables from K8s ConfigMap, that contains plain text key values. How can we use encrypted secrets and load them as variables for the experiment pod

two options: 
- reuse the `env` block, and defines a `secretName` property alongside the `configMapName`. but the enabled flag will be common, not possible to disable only one. 
If the `secretName` is not defined we don't use it. (no default value). this solution could also be used to load both secure/unsecure variables from both K8s ConfigMap & Secret

```yaml
  pod:
    env:
      configMapName: chaostoolkit-env
      secretName: chaostoolkit-secrets
```

- create a new block `secret`, similar to the `env` one.  
```yaml
  pod:
    secret:
      secretName: chaostoolkit-secrets
      enabled: true
```

this solution could be enabled with a default secret name, and be enabled while `env` is disabled. We could also add another property to indicate how to load the secrets , env. vars or mounted file.

**Comment by dmartin35** [comment]
first solution would add a new block in `envFrom` pod definition
```yaml
        envFrom:
        - configMapRef:
            name: chaostoolkit-env
        - secretRef:
            name: chaostoolkit-secrets
```
