### ISSUE TITLE
Schedule & repeat an experiment

### ISSUE THREAD

**Issue by dmartin35** [chaostoolkit-incubator/kubernetes-crd#40]
We could leverage the K8s cronjob to create schedulable / repeatable experiments.

We could add a new block in the CTK object definition to indicate a cron-like scheduling

- very simple definition (similar to K8s CrobJob schedule definition)

```yaml
spec:
  schedule: "*/1 * * * *"
```

- More complex structure (more easily extensible)
```yaml
spec:
  schedule:
    enabled: true
    kind: cronJob
    value: "*/1 * * * *"
```

Do we want to also schedule at a particular day/time  ?
