### ISSUE TITLE
CRD does not respect custom pod image / location

### ISSUE THREAD

**Issue by TGPSKI** [chaostoolkit-incubator/kubernetes-crd#54]
Greetings,

I have been exploring the chaostoolkit k8s-crd as a chaos experiment runner for work. I have struggled a lot with the documentation and examples, and want to provide assistance if possible. Currently, I am unable to progress with any work on chaostoolkit because I cannot get a custom image to be deployed by the crd.

My setup:

- Kubernetes 1.18 on x86_64
- 1 Master / 3 Agents

I have setup the example configuration `generic with RBAC`. Everything matches the example manifests, except for the addition of a custom run image, image pull secrets, and an image pull policy. I've tried two different methods to get the crd watcher to pick up the new pod definition and create the correct pods.

```
    "chaostoolkit-pod.yaml" = <<EOF
apiVersion: v1
kind: Pod
metadata:
  name: chaostoolkit
  labels:
    app: chaostoolkit
spec:
  restartPolicy: Never
  serviceAccountName: chaostoolkit
  containers:
  - name: chaostoolkit
    image: <MY_PRIVATE_REGISTRY>/chaostoolkit:latest
    imagePullPolicy: Always
    command:
    - /usr/local/bin/chaos
    args:
    - run
    - $(EXPERIMENT_PATH)
    env:
    - name: CHAOSTOOLKIT_IN_POD
      value: "true"
    - name: EXPERIMENT_PATH
      value: "/home/svc/experiment.json"
    envFrom:
    - configMapRef:
        name: chaostoolkit-env
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi
    volumeMounts:
    - name: chaostoolkit-settings
      mountPath: /home/svc/.chaostoolkit/
      readOnly: true
    - name: chaostoolkit-experiment
      mountPath: /home/svc/experiment.json
      subPath: experiment.json
      readOnly: true
  volumes:
  - name: chaostoolkit-settings
    secret:
      secretName: chaostoolkit-settings
  - name: chaostoolkit-experiment
    configMap:
      name: chaostoolkit-experiment
  imagePullSecrets:
  - name: regcred
    EOF
```

In the `chaostoolkit-pod.yaml` definition, I have added my custom docker repository, as well as an image pull secret and pull policy. Otherwise, all other fields are the same.

Here's my example experiment:

```
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: chaostoolkit-experiment8
  namespace: chaostoolkit-run
data:
  "experiment.json": |-
    {
        "version": "1.0.0",
        "title": "Moving a file from under our feet is forgivable",
        "description": "Our application should re-create a file that was removed",
        "steady-state-hypothesis": {
            "title": "The file must be around first",
            "probes": [
                {
                    "type": "probe",
                    "name": "file-must-exist",
                    "tolerance": true,
                    "provider": {
                        "type": "python",
                        "module": "os.path",
                        "func": "exists",
                        "arguments": {
                            "path": "/etc"
                        }
                    }
                }
            ]
        },
        "method": [
            {
                "ref": "file-must-exist"
            }
        ]
    }
---
apiVersion: chaostoolkit.org/v1
kind: ChaosToolkitExperiment
metadata:
  name: chaostoolkit-experiment8
  namespace: chaostoolkit-crd
```

When I create these resources, the crd watcher will create a pod in the chaostoolkit-run namespace. Every time, without fail, the created pod uses the "chaostoolkit/chaostoolkit" image. Looking into the config map for `chaostoolkit-resources-templates`, the yaml / json looks valid.

I checked the documentation, and thought perhaps I needed to add the custom spec to the experiment definition. Therefore, I retried multiple times with the following experiment definition:

```
---
apiVersion: chaostoolkit.org/v1
kind: ChaosToolkitExperiment
metadata:
  name: chaostoolkit-experiment8
  namespace: chaostoolkit-crd
spec:
  namespace: chaostoolkit-run
  pod:
    image: <MY_PRIVATE_REGISTRY>/chaostoolkit:latest
    imagePullPolicy: Always
  imagePullSecrets:
  - name: regcred
```

Again, the created pods still use "chaostoolkit/chaostoolkit", and not my custom image.

Where do I go from here?

**Comment by TGPSKI** [comment]
Also, modifying the CRD spec to use the object layout in this PR does not change anything: https://github.com/chaostoolkit-incubator/kubernetes-crd/issues/12

**Comment by TGPSKI** [comment]
After upgrading kopf and kubernetes packages in https://github.com/chaostoolkit-incubator/kubernetes-crd/pull/57, I am able to pull custom images.

**Comment by sonu1311** [comment]
@TGPSKI I just started experimenting with latest chaostoolkit/k8scrd docker image and facing this very same issue. The experiment run pod image always chaostoolkit/chaostoolkit. This is in AKS environment.

**Comment by dmartin35** [comment]
There are two ways to use a custom docker image (instead of the default `chaostoolkit/chaostoolkit:latest` one.

- First, you can override the docker image in the experiment CRO; I added a full example (https://github.com/chaostoolkit-incubator/kubernetes-crd/blob/master/examples/custom-docker-image.yaml)
This solution only supports for image name override, it can not accept `imagePullPolicy` or `imagePullSecrets` at the CRO level (would need to be done in the POD template)

- Second , you can override the default POD template in the ConfigMap, that has to be re-installed. 
You can change the template `chaostoolkit-pod.yaml` in the file https://github.com/chaostoolkit-incubator/kubernetes-crd/blob/d9ee34a885139667c131ed1878d78aa9d05515b4/manifests/base/common/configmap.yaml#L72
Then re-install with ` kustomize ... | kubectl apply -f -  `
In that case, there is no need to indicating the image name in the experiment CRO , it will be the default one used by the CRD when creating pods 

Well, first solution works, but it seems, solution 2 does not work anymore (the pod image with ctk/ctk while the pod template in the config map had chaosiq/ctk)
@sonu1311 if you still have the issue, could you indicate which solution you tried and provide with more information/logs, thanks , and please try solution 1

*Tested with docker-desktop v2.4.0.0 running Kubernetes v1.18.8*

**Comment by dmartin35** [comment]
Issues comes from the following line 
https://github.com/chaostoolkit-incubator/kubernetes-crd/blob/d9ee34a885139667c131ed1878d78aa9d05515b4/controller.py#L585

When we check the CRO definition, we check whether the image is overridden, otherwise we use the default CTK image; but we do not care about the pod template image from the config map

**Comment by dmartin35** [comment]
I think both use cases are now fixed, but if you guys still have an issue, please feel free to re-open

**Comment by dmartin35** [comment]
fixed by #67

**Comment by klusht** [comment]
Just to clarify the usage of custom images from private registries: Edit the config map list entry to add the imagePullSecrets  directive, as the override from ChaosToolkitExperiment kind  did not work for me. 
In case you use kustomize add a patchesStrategicMerge with:
```
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: chaostoolkit-crd
    provider: chaostoolkit
    role: chaosengineering
  name: chaostoolkit-resources-templates
  namespace: chaostoolkit-crd
data:
  chaostoolkit-pod.yaml: |-
    apiVersion: v1
    kind: Pod
    metadata:
      name: chaostoolkit
      labels:
        app: chaostoolkit
    spec:
      restartPolicy: Never
      serviceAccountName: chaostoolkit
      imagePullSecrets:
        - name: private-registry-secret         <<<<------- your private registry secret key
      containers:
      - name: chaostoolkit
        image: registry/myspecialchaostoolkit:v1.0    <<<<-------- your custom image
        imagePullPolicy: Always
[... add the entire yaml]
```
