### ISSUE TITLE
Add shortcut to support `chaos verify`command

### ISSUE THREAD

**Issue by dmartin35** [chaostoolkit-incubator/kubernetes-crd#7]
From now on, the chaos experiment template only support the `chaos run` command.

We can override this command, but it requires to pass the entire pod template, which is a bit complex just to `verify` instead of `run`.

I suggest we add at chaos experiment spec level an option to easily switch to verify mode `runAsVerification: true`

```
---
apiVersion: chaostoolkit.org/v1
kind: ChaosToolkitExperiment
metadata:
  name: my-chaos-verif
  namespace: chaostoolkit-crd
spec:
  namespace: chaostoolkit-run
  pod:
    image:
      name: chaosiq/chaostoolkit
    runAsVerification: true
```
